### ISSUE TITLE
xamarin-components-restore - (503) Service Unavailable

### ISSUE THREAD

**Issue by squallu** [bitrise-steplib/steps-xamarin-components-restore#4] opened 2017-05-31 14:53 UTC
Hi,
Is it either my fault or I just have bad luck?:)

Cheers

```
+------------------------------------------------------------------------------+
| (5) xamarin-components-restore@0.9.0                                         |
+------------------------------------------------------------------------------+
| id: xamarin-components-restore                                               |
| version: 0.9.0                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2017-05-31T07:44:48-07:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |

========== Configs ==========
 * xamarin_solution: Mobile/Mobile.sln

mono /Users/vagrant/bitrise/xamarin/xamarin-component/xamarin-component.exe restore Mobile/Mobile.sln
INFO (restore): Computed cookie jar path: /Users/vagrant/.xamarin-credentials
INFO (restore): [*] Restoring hockeyappandroid v4.1.2.0
INFO (restore): Downloading hockeyappandroid 4.1.2.0
INFO (check): Computed cookie jar path: /Users/vagrant/.xamarin-credentials
INFO (check): Checking for component `hockeyappandroid' on components.xamarin.com...
INFO (check): Computed cookie jar path: /Users/vagrant/.xamarin-credentials
INFO (check): Loading cookie jar from /Users/vagrant/.xamarin-credentials.
INFO (check): Adding cookie for xamarin.com.

Unhandled Exception:
System.Net.WebException: The remote server returned an error: (503) Service Unavailable.
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00058] in <5afdc70d980c4033b3878286f754d091>:0 
  at System.Net.HttpWebRequest.GetResponse () [0x0000e] in <5afdc70d980c4033b3878286f754d091>:0 
  at Xamarin.Components.CheckCommandHandler.GetAvailableVersions (System.String server, System.String alias) [0x0002f] in <e1e0156428194e0e90c81cad9f4afc9b>:0 
  at Xamarin.Components.CheckCommandHandler.Invoke (System.String[] args) [0x000eb] in <e1e0156428194e0e90c81cad9f4afc9b>:0 
  at Xamarin.Components.Utility.RunCheckWorkflowForComponent (Xamarin.Components.ICommandHandler handler, System.Boolean staging, System.Boolean development, System.String id, System.String version) [0x00089] in <e1e0156428194e0e90c81cad9f4afc9b>:0 
  at Xamarin.Components.RestoreCommandHandler.DownloadComponentFromServer (System.String server, System.String componentId, System.String componentVersion, System.Boolean isTrial) [0x0015c] in <e1e0156428194e0e90c81cad9f4afc9b>:0 
  at Xamarin.Components.RestoreCommandHandler.Invoke (System.String[] args) [0x002f1] in <e1e0156428194e0e90c81cad9f4afc9b>:0 
  at Xamarin.Components.MainClass.Main (System.String[] args) [0x00056] in <e1e0156428194e0e90c81cad9f4afc9b>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.Net.WebException: The remote server returned an error: (503) Service Unavailable.
  at System.Net.HttpWebRequest.EndGetResponse (System.IAsyncResult asyncResult) [0x00058] in <5afdc70d980c4033b3878286f754d091>:0 
  at System.Net.HttpWebRequest.GetResponse () [0x0000e] in <5afdc70d980c4033b3878286f754d091>:0 
  at Xamarin.Components.CheckCommandHandler.GetAvailableVersions (System.String server, System.String alias) [0x0002f] in <e1e0156428194e0e90c81cad9f4afc9b>:0 
  at Xamarin.Components.CheckCommandHandler.Invoke (System.String[] args) [0x000eb] in <e1e0156428194e0e90c81cad9f4afc9b>:0 
  at Xamarin.Components.Utility.RunCheckWorkflowForComponent (Xamarin.Components.ICommandHandler handler, System.Boolean staging, System.Boolean development, System.String id, System.String version) [0x00089] in <e1e0156428194e0e90c81cad9f4afc9b>:0 
  at Xamarin.Components.RestoreCommandHandler.DownloadComponentFromServer (System.String server, System.String componentId, System.String componentVersion, System.Boolean isTrial) [0x0015c] in <e1e0156428194e0e90c81cad9f4afc9b>:0 
  at Xamarin.Components.RestoreCommandHandler.Invoke (System.String[] args) [0x002f1] in <e1e0156428194e0e90c81cad9f4afc9b>:0 
  at Xamarin.Components.MainClass.Main (System.String[] args) [0x00056] in <e1e0156428194e0e90c81cad9f4afc9b>:0 `
```

**Comment by viktorbenei** [comment] 2017-05-31 15:04
Hi,

Did you try a rebuild?

**Comment by viktorbenei** [comment] 2017-05-31 15:05
Seems like a Xamarin server issue:

```
[ERROR] FATAL UNHANDLED EXCEPTION: System.Net.WebException: The remote server returned an error: (503) Service Unavailable.
```

**Comment by squallu** [comment] 2017-05-31 15:09
Yes, I did rebuild twice.

> Seems like a Xamarin server issue

I was afraid of that.. Now I can only wait, right?

**Comment by viktorbenei** [comment] 2017-05-31 15:11
If this keeps happening I'd suggest you to contact their support, to see if they know about the issue and for any estimation about a fix

**Comment by andredestro** [comment] 2017-05-31 18:10
it be the same problem?

```
+------------------------------------------------------------------------------+
| (3) xamarin-components-restore                                               |
+------------------------------------------------------------------------------+
| id: xamarin-components-restore                                               |
| version: 0.9.0                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2017-05-31T11:03:32-07:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |

========== Configs ==========
 * xamarin_solution: offline/Mobile/ProjectMobile.sln

mono /Users/vagrant/bitrise/xamarin/xamarin-component/xamarin-component.exe restore offline/ProjectMobile/ProjectMobile.sln
INFO (restore): Computed cookie jar path: /Users/vagrant/.xamarin-credentials
INFO (restore): [*] Restoring json.net v4.5.11.1
INFO (restore): Downloading json.net 4.5.11.1
INFO (check): Computed cookie jar path: /Users/vagrant/.xamarin-credentials
INFO (check): Checking for component `json.net' on components.xamarin.com...
INFO (check): Computed cookie jar path: /Users/vagrant/.xamarin-credentials
INFO (check): Loading cookie jar from /Users/vagrant/.xamarin-credentials.
INFO (check): Adding cookie for xamarin.com.
INFO (check): Verified that component exists.
INFO (restore): Computed cookie jar path: /Users/vagrant/.xamarin-credentials
INFO (restore): Loading cookie jar from /Users/vagrant/.xamarin-credentials.
INFO (restore): Adding cookie for xamarin.com.
ERROR (restore): Failed to download json.net-4.5.11.1.png: The remote server returned an error: (500) Internal Server Error.
INFO (restore): Computed cookie jar path: /Users/vagrant/.xamarin-credentials
INFO (restore): Loading cookie jar from /Users/vagrant/.xamarin-credentials.
INFO (restore): Adding cookie for xamarin.com.
INFO (restore): Computed cookie jar path: /Users/vagrant/.xamarin-credentials
INFO (restore): Loading cookie jar from /Users/vagrant/.xamarin-credentials.
INFO (restore): Adding cookie for xamarin.com.
ERROR (restore): Failed to download json.net-4.5.11.1.xam: The remote server returned an error: (403) Forbidden.
INFO (restore): [*] Successfully restored json.net v4.5.11.1
INFO (restore): [*] Restoring NineOldAndroids v2.4.0
INFO (restore): Downloading NineOldAndroids 2.4.0
INFO (check): Computed cookie jar path: /Users/vagrant/.xamarin-credentials
INFO (check): Checking for component `NineOldAndroids' on components.xamarin.com...
INFO (check): Computed cookie jar path: /Users/vagrant/.xamarin-credentials
INFO (check): Loading cookie jar from /Users/vagrant/.xamarin-credentials.
INFO (check): Adding cookie for xamarin.com.
INFO (check): Verified that component exists.
INFO (restore): Computed cookie jar path: /Users/vagrant/.xamarin-credentials
INFO (restore): Loading cookie jar from /Users/vagrant/.xamarin-credentials.
INFO (restore): Adding cookie for xamarin.com.
ERROR (restore): Failed to download NineOldAndroids-2.4.0.png: The remote server returned an error: (500) Internal Server Error.
INFO (restore): Computed cookie jar path: /Users/vagrant/.xamarin-credentials
INFO (restore): Loading cookie jar from /Users/vagrant/.xamarin-credentials.
INFO (restore): Adding cookie for xamarin.com.
INFO (restore): Computed cookie jar path: /Users/vagrant/.xamarin-credentials
INFO (restore): Loading cookie jar from /Users/vagrant/.xamarin-credentials.
INFO (restore): Adding cookie for xamarin.com.
ERROR (restore): Failed to download NineOldAndroids-2.4.0.xam: The remote server returned an error: (403) Forbidden.

Unhandled Exception:
System.IO.DirectoryNotFoundException: Destination directory not found: /Users/vagrant/git/offline/ProjectMobile/Components
  at System.IO.File.Copy (System.String sourceFileName, System.String destFileName, System.Boolean overwrite) [0x00162] in <ffb99659fc1c47faa4d5f883014d08aa>:0 
  at Xamarin.Components.RestoreCommandHandler.RestoreComponentIntoSolution (System.String componentId, System.String componentVersion, System.Boolean isTrial, System.String destinationDirectoryForRestore) [0x00141] in <e1e0156428194e0e90c81cad9f4afc9b>:0 
  at Xamarin.Components.RestoreCommandHandler.Invoke (System.String[] args) [0x00314] in <e1e0156428194e0e90c81cad9f4afc9b>:0 
  at Xamarin.Components.MainClass.Main (System.String[] args) [0x00056] in <e1e0156428194e0e90c81cad9f4afc9b>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.DirectoryNotFoundException: Destination directory not found: /Users/vagrant/git/offline/ProjectMobile/Components
  at System.IO.File.Copy (System.String sourceFileName, System.String destFileName, System.Boolean overwrite) [0x00162] in <ffb99659fc1c47faa4d5f883014d08aa>:0 
  at Xamarin.Components.RestoreCommandHandler.RestoreComponentIntoSolution (System.String componentId, System.String componentVersion, System.Boolean isTrial, System.String destinationDirectoryForRestore) [0x00141] in <e1e0156428194e0e90c81cad9f4afc9b>:0 
  at Xamarin.Components.RestoreCommandHandler.Invoke (System.String[] args) [0x00314] in <e1e0156428194e0e90c81cad9f4afc9b>:0 
  at Xamarin.Components.MainClass.Main (System.String[] args) [0x00056] in <e1e0156428194e0e90c81cad9f4afc9b>:0 
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | xamarin-components-restore (exit code: 1)                     | 7.10 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...om/bitrise-steplib/steps-xamarin-components-restore/issues |
| Source: ...//github.com/bitrise-steplib/steps-xamarin-components-restore.git |
+---+---------------------------------------------------------------+----------+
```

**Comment by biehlio** [comment] 2017-05-31 18:25
The xamarin components service was down for a while this morning. It seems to be up now but this step is also failing for me with the error above from @andredestro 

Seems to still be an issue with xam components service with all the 403's and 500's

**Comment by DrBilitski** [comment] 2017-05-31 19:24
Just an update.  In Xamarin studio and Visual Studio for mac, components store can be viewed but ultimately the component does not download.  It returns a (403) forbidden error within the IDE.

**Comment by lnpquang** [comment] 2017-06-01 06:44
Dear all,
I get the same issue.
Is there any update for this?

Thanks all.
Best regards.

**Comment by mxpmd03** [comment] 2017-06-01 10:00
same issue.
Any update on this?

Thanks.
Best regards.

**Comment by viktorbenei** [comment] 2017-06-01 10:01
@mxpmd03 @lnpquang did you try to contact Xamarin support? The issue seems to be on the xamarin components server side, unfortunately we can't do anything about that.

In the meantime we also contacted them, waiting for a response.

**Comment by biehlio** [comment] 2017-06-01 15:26
As of this writing, I am no longer having the xam component restore step failing for me. Seems the server issues are gone.

**Comment by lnpquang** [comment] 2017-06-01 15:28
yes, i think server is ok now :)

**Comment by viktorbenei** [comment] 2017-06-01 15:31
Awesome to hear, thanks for reporting @realdealbiehl & @lnpquang ! :)

**Comment by viktorbenei** [comment] 2017-06-01 16:40
We received a reply from Xamarin that there was some ongoing migration which might have caused the issue, but the migration is finished now and everything should work again as expected - which seems to be confirmed by @realdealbiehl & @lnpquang ;)

We'll close this issue now, if you'd still see this happen again please let us know and we'll reopen it!

**Closed as completed by viktorbenei** 2017-06-01 16:40 UTC

**Comment by lnpquang** [comment] 2017-06-01 17:47
Thank you so much!
